package hotelmanagement;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

class payment {

    private Connection sqlConnection;
    private String user, password, id;
    private Date date;
    private PreparedStatement markAsPaid;
    private SimpleDateFormat invoiceDateFormat;
    private double total, serviceTax, tourismTax, grandTotal, balance;

    payment() {
        sqlConnection = null;
        user = "root";
        password = "";
        invoiceDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    }

    public void setId(String ID) {
        id = ID;
    }

    public String getCurrentDate() {
        return invoiceDateFormat.format(date);
    }

    public double getTotal() {
        return total;
    }

    public double getServiceTax() {
        return serviceTax;
    }

    public double getTourisnTax() {
        return tourismTax;
    }

    public double getGrandtotal() {
        return grandTotal;
    }

    public double getBalance() {
        return balance;
    }

    public void currentDate() {
        date = new Date();
    }

    public void calculateTotal(String stay) {
        total = Integer.parseInt(stay) * 350;
        serviceTax = total * 0.10;
        tourismTax = Integer.parseInt(stay) * 10;
        grandTotal = total + serviceTax + tourismTax;
    }

    public void calculate(String paid) {
        balance = Integer.parseInt(paid) - grandTotal;
    }

    public void markAsPaid(int result) {
        if (result == 0) {
            //mark as paid
            try {
                sqlConnection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagement?serverTimezone=UTC", user, password);
                markAsPaid = sqlConnection.prepareStatement("UPDATE booking SET Payment_Status = ? WHERE Id = '" + id + "'");
                markAsPaid.setString(1, "Paid");
                markAsPaid.executeUpdate();

            } catch (Exception exc) {
                exc.printStackTrace();
            }
        } else {
            //do nothing
        }
    }
}

public class MakePayment extends javax.swing.JDialog {
    payment payment = new payment();
    DecimalFormat df = new DecimalFormat("#,###.00");
    public MakePayment(java.awt.Frame parent, boolean modal, ArrayList<String> returnSelected) {
        super(parent, modal);
        initComponents();
        btnPrint.setEnabled(false);
        btnPay.setEnabled(false);
        if (returnSelected.get(6).toString().compareTo("Paid") == 0) {
            btnPrint.setEnabled(true);
        }
        payment.setId(returnSelected.get(0).toString());
        payment.currentDate();
        payment.calculateTotal(returnSelected.get(4));
        txtReceipt.setText(
                "Invoice\t\t\t Date: " + payment.getCurrentDate()
                + "\nNo: " + returnSelected.get(0).toString()
                + "\nName: " + returnSelected.get(1).toString()
                + "\nCheck-in Date: " + returnSelected.get(2).toString() + "\tCheck-out Date: " + returnSelected.get(3).toString()
                + "\nNight: " + returnSelected.get(4).toString()
                + "\n--------------------------------------------------------------------------------------------------------"
                + "\nRoom\t Number of Night(s)\t\tTotal"
                + "\n--------------------------------------------------------------------------------------------------------"
                + "\nRoom " + returnSelected.get(5).toString() + "\t" + returnSelected.get(4).toString() + "\t\t\t" + df.format(payment.getTotal())
                + "\n\n\nService Tax (10%): \t\t\t" + df.format(payment.getServiceTax())
                + "\nTourism Tax RM10 / Night: \t\t\t" + df.format(payment.getTourisnTax())
                + "\nGrand Total: RM" + "\t\t\t" + df.format(payment.getGrandtotal())
        );
        txtGrandTotal.setText(df.format(payment.getGrandtotal()));
        this.getContentPane().setBackground(new Color(243, 244, 246));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        txtGrandTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        lblGrandTotal = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Make Payment");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Invoice");

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        btnCancel.setBackground(new java.awt.Color(31, 41, 55));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtGrandTotal.setEditable(false);
        txtGrandTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGrandTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrandTotalActionPerformed(evt);
            }
        });

        jLabel1.setText("Grand Total (RM)");

        jLabel2.setText("Paid (RM)");

        txtPaid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaidKeyReleased(evt);
            }
        });

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });

        jLabel3.setText("Balance (RM)");

        btnPrint.setBackground(new java.awt.Color(31, 41, 55));
        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(31, 41, 55));
        btnPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        lblGrandTotal.setBackground(new java.awt.Color(243, 244, 246));
        lblGrandTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblGrandTotal.setOpaque(true);
        lblGrandTotal.setPreferredSize(new java.awt.Dimension(15, 24));

        lblBalance.setBackground(new java.awt.Color(243, 244, 246));
        lblBalance.setForeground(new java.awt.Color(255, 0, 0));
        lblBalance.setOpaque(true);
        lblBalance.setPreferredSize(new java.awt.Dimension(15, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPrint)
                                .addGap(18, 18, 18)
                                .addComponent(btnPay)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(38, 38, 38)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(19, 19, 19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGrandTotal)
                                    .addComponent(txtBalance, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPaid)))
                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrint)
                            .addComponent(btnPay)
                            .addComponent(btnCancel))))
                .addGap(64, 64, 64))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtGrandTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrandTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrandTotalActionPerformed

    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            txtReceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(MakePayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        int result = JOptionPane.showConfirmDialog(this,
                "Please return the balance of RM " + df.format(payment.getBalance()),
                "Booking Payment",
                JOptionPane.YES_NO_OPTION);
        payment.markAsPaid(result);
    }//GEN-LAST:event_btnPayActionPerformed

    private void txtPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyReleased
        if (!Pattern.matches("^[0-9]+$", txtPaid.getText())) {
            lblGrandTotal.setText("Paid amount can contain numbers only.");
        } else {
            lblGrandTotal.setText("");
            payment.calculate(txtPaid.getText());
            txtBalance.setText(df.format(payment.getBalance()));
            if (payment.getBalance() >= 0) {
                btnPrint.setEnabled(true);
                btnPay.setEnabled(true);
                lblBalance.setText("");
            } else {
                lblBalance.setText("Amount Paid is less than Grand Total.");
                btnPrint.setEnabled(false);
                btnPay.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtPaidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MakePayment dialog = new MakePayment(new javax.swing.JFrame(), true, new ArrayList<String>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
